import { Instrument_Sans, Inter, Mulish } from "next/font/google";
import "./globals.css";
import Header from "@/components/global";
import Footer from "@/components/global/Footer";
import ScrollToTop from "@/components/global/ScrollToTop";
import Script from "next/script";

const instrument = Instrument_Sans({
  // weight: ['400', '700', '200'],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Starconcord",
  description: "Generated by Starconcord",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={instrument.className}>
        <Script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
            var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
            (function(){
              var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
              s1.async=true;
              s1.src='https://embed.tawk.to/6735c3234304e3196ae274fe/1icl04gt2';
              s1.charset='UTF-8';
              s1.setAttribute('crossorigin','*');
              s0.parentNode.insertBefore(s1,s0);
            })();
          `,
          }}
        ></Script>
        <Header />
        {children}
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}
