import { Instrument_Sans, Inter, Mulish } from 'next/font/google';
import './globals.css';
import Header from '@/components/global';
import Footer from '@/components/global/Footer';
import ScrollToTop from '@/components/global/ScrollToTop';

const instrument = Instrument_Sans({
    // weight: ['400', '700', '200'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

export const metadata = {
    title: 'Starconcord',
    description: 'Generated by Starconcord',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={instrument.className}>
                <Header />
                {children}
                <ScrollToTop />
                <Footer />
            </body>
        </html>
    );
}
